### ISSUE TITLE
Setup local instance Error

### ISSUE THREAD

**Issue by ByzanTine** [Stanford-IoT-Lab/thingengine-platform-cloud#1]
npm ERR! journald@0.0.5 preinstall: `node-gyp clean && node-gyp configure`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the journald@0.0.5 preinstall script 'node-gyp clean && node-gyp configure'.
npm ERR! This is most likely a problem with the journald package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp clean && node-gyp configure
npm ERR! You can get their info via:
npm ERR!     npm owner ls journald
npm ERR! There is likely additional logging output above.

**Comment by ByzanTine** [comment]
Also can you specify what are the pre-requisite for installing this?
Like node-js, npm? Versions?

**Comment by gcampax** [comment]
Prereq for selfcontained is any Linux distro. I tested nodejs 0.12 but newer should work. Arch is x86_64 but hopefully does not matter.

journald is not actually required, I forgot the dep in package.json when I was making the selfcontained branch, I fixed it now.

**Comment by ByzanTine** [comment]
I can make now.
But I can this message when I run 
Express server listening on port 8080
Starting AssistantDispatcher
Starting EngineManager
/home/jiayuye/Downloads/thingengine-platform-cloud/node_modules/q/q.js:155
                throw e;
                      ^
Error: ER_NO_SUCH_TABLE: Table 'thingengine_selfcontained.users' doesn't exist
    at Query.Sequence._packetToError (/home/jiayuye/Downloads/thingengine-platform-cloud/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/home/jiayuye/Downloads/thingengine-platform-cloud/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/home/jiayuye/Downloads/thingengine-platform-cloud/node_modules/mysql/lib/protocol/Protocol.js:274:23)
    at Parser.write (/home/jiayuye/Downloads/thingengine-platform-cloud/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/home/jiayuye/Downloads/thingengine-platform-cloud/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/jiayuye/Downloads/thingengine-platform-cloud/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
    --------------------
    at Protocol._enqueue (/home/jiayuye/Downloads/thingengine-platform-cloud/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at PoolConnection.query (/home/jiayuye/Downloads/thingengine-platform-cloud/node_modules/mysql/lib/Connection.js:201:25)
From previous event:
    at /home/jiayuye/Downloads/thingengine-platform-cloud/enginemanager.js:230:40
    at /home/jiayuye/Downloads/thingengine-platform-cloud/util/db.js:83:20
make: *** [run] Error 1

**Comment by gcampax** [comment]
Did you run all of make, including the part where it asks for the mysql password?
That should have created the tables.

Try "make database-force" to create them again.

**Comment by ByzanTine** [comment]
I did do the mysql setup.
But when I run it again I got this
mysql -u root -p < model/schema.sql
Enter password: 
ERROR 1067 (42000) at line 21: Invalid default value for 'developer_key'
make: *** [database-force] Error 1

**Comment by gcampax** [comment]
Another user reported this and I found a problem in the SQL code. Should be fixed now, please pull and run make database-force again.

**Comment by ByzanTine** [comment]
Looks good now thx.
